<a href="https://colab.research.google.com/github/janesh-kiddev/python-files/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np


In [5]:
ar = np.array([23,3,3,3,3,3])
print(ar)
dr = np.array(45)
print(dr)

[23  3  3  3  3  3]
45


In [6]:
darry = np.array([[1,2,3],[4,5,6]])
print(darry)
# displays the dimension
print(darry.ndim)

[[1 2 3]
 [4 5 6]]
2


In [7]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)
k = np.array([1,2,2])
#indexing
print(k[0])

[[[[[1 2 3 4]]]]]
number of dimensions : 5
1


In [8]:
catch = np.array([[1, 2, 3, 4],[6, 7, 8, 9]])
#silcing
print(catch[1,1])


7


In [9]:
#access the values from start to endpoint
np.arange(50,60,1)
np.arange(50,60,2)

array([50, 52, 54, 56, 58])

In [10]:
#to get the random numbers in float
np.random.uniform(5,10,size=4)
np.random.uniform(10,15,size = 10)

array([11.16801038, 12.44432452, 14.60308456, 14.42879214, 14.80017493,
       11.36367008, 12.18090679, 14.35662143, 13.77196561, 11.98604588])

In [11]:
np.random.uniform(50,60,size = 6)


array([57.77549383, 59.52110193, 50.57696533, 52.3552636 , 59.58614267,
       53.38450153])

In [12]:
# generate random numbers in float
np.random.rand(1,2)
np.random.rand(10,12)

array([[0.39674228, 0.83176803, 0.23060072, 0.29333329, 0.23139277,
        0.56501241, 0.71915745, 0.17348288, 0.86385359, 0.3010323 ,
        0.87245994, 0.92220043],
       [0.01933875, 0.57609688, 0.23274058, 0.77268729, 0.13056514,
        0.81862065, 0.96021451, 0.05226272, 0.85971995, 0.09965244,
        0.21312782, 0.3703566 ],
       [0.21355299, 0.79483393, 0.86682888, 0.94690961, 0.94003246,
        0.33532203, 0.42838688, 0.23326263, 0.22797385, 0.13238103,
        0.42301151, 0.6350078 ],
       [0.71416486, 0.87244642, 0.93675337, 0.3944651 , 0.03737033,
        0.32688656, 0.55800347, 0.08387553, 0.1377947 , 0.65454812,
        0.57395382, 0.90559328],
       [0.3193629 , 0.62088547, 0.73650677, 0.37193937, 0.4565153 ,
        0.67085452, 0.31120176, 0.88963136, 0.23642749, 0.36469996,
        0.18192105, 0.13522852],
       [0.43283362, 0.10888293, 0.46114365, 0.68185676, 0.4944934 ,
        0.18427099, 0.507355  , 0.41296497, 0.684322  , 0.75646239,
        0.14915779,

In [13]:
np.random.random_integers(1,10)#return sthe random intgers

<ipython-input-13-e8037d6a3438>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  np.random.random_integers(1,10)#return sthe random intgers


10

In [14]:
dr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(dr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [15]:
print(dr.dtype)# represent the datatype
print(dr.itemsize)#displays th item size
print(dr.ndim)# display the size of aray
print(dr.shape)#returns the rows and colums
print(dr.nbytes)#retruns the bytes
print(dr.size)#retrns the totla element present in it

int64
8
2
(2, 5)
80
10


In [16]:
dx = np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]],[[13,14,15,16,17,18],[19,20,21,22,23,24]]])
print(dx)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]]


In [17]:
arr = np.array([[0,1,2,3,4,5]])
print(arr)
y = [arr % 2 == 0]
print(y)

[[0 1 2 3 4 5]]
[array([[ True, False,  True, False,  True, False]])]


In [18]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
arr[0][1]

2

In [20]:
arr[:,1:3]

array([[2, 3],
       [7, 8]])

In [22]:
print(arr.shape)

(2, 5)


In [23]:
arr[0,2:3] = [0]

In [27]:
arr[1] = [12,13,14,15,16]

In [28]:
arr

array([[ 1,  2,  0,  4,  5],
       [12, 13, 14, 15, 16]])

broadcasting

In [30]:
np.array([[1,2,3],[4,5,6]])+np.array([[1,2,3],[4,5,6]])

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [31]:
np.array([10,1,34])+np.array([100,200,300])

array([110, 201, 334])

In [34]:
np.random.randint(1,9,size=(4,4))

array([[6, 3, 1, 5],
       [8, 8, 3, 3],
       [6, 7, 7, 5],
       [8, 2, 2, 8]])

In [35]:
a = np.zeros((10,10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
rep = np.repeat(arr, 4, axis=0)
print(rep)
print(rep.shape)

[[ 1  2  0  4  5]
 [ 1  2  0  4  5]
 [ 1  2  0  4  5]
 [ 1  2  0  4  5]
 [12 13 14 15 16]
 [12 13 14 15 16]
 [12 13 14 15 16]
 [12 13 14 15 16]]
(8, 5)


In [39]:
arr2 = arr.copy()
arr2

array([[ 1,  2,  0,  4,  5],
       [12, 13, 14, 15, 16]])

In [42]:
np.random.randint(1,10,size=(5,5))

array([[4, 4, 1, 4, 4],
       [6, 9, 2, 7, 1],
       [3, 5, 1, 5, 6],
       [5, 3, 2, 7, 5],
       [1, 3, 9, 9, 7]])

In [47]:
ar = np.array([1,2,3,4,5])
ab = np.array([4,5,6,7,8])

print(np.vstack([ar,ab,ar,ab]))
print(np.hstack([ab,ab,ar]))

[[1 2 3 4 5]
 [4 5 6 7 8]
 [1 2 3 4 5]
 [4 5 6 7 8]]
[4 5 6 7 8 4 5 6 7 8 1 2 3 4 5]
