<a href="https://colab.research.google.com/github/janesh-kiddev/python-files/blob/main/numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
ar = np.array([23,3,3,3,3,3])
print(ar)
dr = np.array(45)
print(dr)

[23  3  3  3  3  3]
45


In [ ]:
darry = np.array([[1,2,3],[4,5,6]])
print(darry)
# displays the dimension
print(darry.ndim)

[[1 2 3]
 [4 5 6]]
2


In [34]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)
k = np.array([1,2,2])
#indexing
print(k[0])

[[[[[1 2 3 4]]]]]
number of dimensions : 5
1


In [ ]:
catch = np.array([[1, 2, 3, 4],[6, 7, 8, 9]])
#silcing
print(catch[1,1])


7


In [19]:
#access the values from start to endpoint
np.arange(50,60,1)
np.arange(50,60,2)

array([50, 52, 54, 56, 58])

In [20]:
#to get the random numbers in float
np.random.uniform(5,10,size=4)
np.random.uniform(10,15,size = 10)

array([11.3843963 , 14.47653465, 13.14007609, 10.87468485, 11.49464989,
       11.75208327, 11.70151748, 14.60287534, 13.6864829 , 12.51117483])

In [ ]:
np.random.uniform(50,60,size = 6)


array([58.40544912, 59.60193908, 50.86753032, 50.0229582 , 53.32465565,
       59.72250703])

In [21]:
# generate random numbers in float
np.random.rand(1,2)
np.random.rand(10,12)

array([[0.28429694, 0.80204447, 0.43784767, 0.95681723, 0.73278024,
        0.44437223, 0.23064376, 0.85073369, 0.34548332, 0.36377161,
        0.34990244, 0.29181942],
       [0.09406151, 0.80341521, 0.27963075, 0.42353504, 0.1707698 ,
        0.30971355, 0.64372067, 0.20617016, 0.53138997, 0.1485692 ,
        0.01770355, 0.34867807],
       [0.81670108, 0.33926732, 0.3606786 , 0.38034313, 0.12172289,
        0.67773468, 0.86924009, 0.6003458 , 0.51574862, 0.57725878,
        0.69167231, 0.7874419 ],
       [0.02767362, 0.95742899, 0.02215841, 0.33414555, 0.48881239,
        0.98204254, 0.17275016, 0.01338197, 0.71806973, 0.05554771,
        0.77253216, 0.94802514],
       [0.45881948, 0.06546004, 0.27559806, 0.76927674, 0.33646929,
        0.52895153, 0.3604541 , 0.53104056, 0.2768851 , 0.49072888,
        0.494298  , 0.36924575],
       [0.92573075, 0.360481  , 0.0678856 , 0.09440896, 0.37400395,
        0.80686024, 0.35164085, 0.86563914, 0.10526049, 0.30768226,
        0.93160607,

In [23]:
np.random.random_integers(1,10)#return sthe random intgers

<ipython-input-23-c8e21f3575da>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  np.random.random_integers(1,10)


4

data type int64
matrix shape (1, 1, 1, 1, 4)
dimension 5
size 4
item size in Bytes 8
array size in Bytes 32


In [16]:
dr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(dr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [31]:
print(dr.dtype)# represent the datatype
print(dr.itemsize)#displays th item size
print(dr.ndim)# display the size of aray
print(dr.shape)#returns the rows and colums
print(dr.nbytes)#retruns the bytes
print(dr.size)#retrns the totla element present in it

int64
8
2
(2, 5)
80
10


In [33]:
dx = np.array([[[1,2,3,4,5,6],[7,8,9,10,11,12]],[[13,14,15,16,17,18],[19,20,21,22,23,24]]])
print(dx)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]]


In [41]:
arr = np.array([[0,1,2,3,4,5]])
print(arr)
y = [arr % 2 == 0]
print(y)

[[0 1 2 3 4 5]]
[array([[ True, False,  True, False,  True, False]])]


In [44]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
arr[0][1]

2

In [48]:
arr[:,1:3]

array([[2, 3],
       [7, 8]])